### ISSUE TITLE
Exported clipboard QIDs will not show from highlighted cards 

### ISSUE THREAD

**Issue by lwoods1** [AnKing-VIP/ankiweb-placeholder#40]
## Which add-on is this about?
UWorld QID to anki search v 1.16

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Installed the addon, went through all steps as listed in Bronze Anki Tier page in ankipalace. First I ensured that v12 and Step 1 were correct in the Anki Browser. Then I imported all my previous UWorld blocks QIDs into the addon as per instruction. Then, I found a tag I wanted to build a UWorld question set from: tag:AnkiHub\_Optional::UofU::B&B and selected all cards. Then I went to the UWorld--> export 40 highighted cards and got this message: 

You just copied some uworld question ids to your clipboard. Should these excluded from future question id exports/runs of this command?

Before answering this question you could paste your clipboard content into uworld and review the questions there and then return here to answer this question.

Even if you answer 'yes' here you can still revert the exclusion of the question-ids from this export by editing the following json file

C:\Users\lacey\AppData\Roaming\Anki2\addons21\607963104\user_files\already_exported_qids.json

Use a text editor. That's kind of complicated but whenever you change an add-on config you already edit json files.

So should the copied question ids excluded from future question id exports/runs of this command?

I clicked no and failed to see any QID's exported. I tried it again and this time answered "yes" and still no QIDs appeared. I tried disabling all addons except for AnkiHub and this addon and it still would not show clipboard. Also, this issue was present when I was on 2.1.57

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X ] I've restarted Anki to see if it helps
 - [ X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X  ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? v12

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.58
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AbdullahOmira** [comment]
The issue hasn't been resolved. Tried anki-2.1.56, ⁨2.1.61. both 1.16, 1.19 versions of the addon.

**Comment by DoctorToBeIn23** [comment]
So are you saying that no matter what you can no longer export QIDs?

**Comment by AbdullahOmira** [comment]
It's the first time using the addon. all good except the export thing. I posted this on ankiweb before i got here:
It says, "You just copied some UWorld question IDs to your clipboard. Should these be excluded from future question ID exports/runs of this command?"
but nothing has really been copied to the clipboard. It only exports IDs to the file: AppData\Roaming\Anki2\addons21\607963104\user_files\already_exported_qids.json.

**Comment by DoctorToBeIn23** [comment]
Make sure you are highlighting all the cards you want it to pull from, this sometimes is the issue. Please send screenshots of each step your doing so we can figure out where the issue is.

**Comment by AbdullahOmira** [comment]
Here, 
![image](https://user-images.githubusercontent.com/77205655/235769004-fe881e3f-c5f0-45f9-a1a6-3acadda73e7f.png)
![image](https://user-images.githubusercontent.com/77205655/235769123-30e8ea83-cc85-4433-8e50-40b332c9c2e0.png)
![image](https://user-images.githubusercontent.com/77205655/235769277-8b6bbdaf-6530-4fef-9c04-06613ccf346e.png)
![image](https://user-images.githubusercontent.com/77205655/235769322-b76b8da6-e3c3-4ae5-a3d3-dc3964094347.png)
![image](https://user-images.githubusercontent.com/77205655/235769354-94140419-45f1-4b9b-8f06-ff41c68c79fa.png)
![image](https://user-images.githubusercontent.com/77205655/235769429-93cb6654-25ad-4bb1-91b0-78819f3b5c83.png)
![image](https://user-images.githubusercontent.com/77205655/235769454-8a585563-269f-448c-8046-7d6e14584d37.png)
![image](https://user-images.githubusercontent.com/77205655/235769483-e678dc36-f833-4950-b311-13f67505ae62.png)

**Comment by DoctorToBeIn23** [comment]
This seems to be an issue with Windows, I just did the same thing on the Mac with no issues at all. I am wondering if there is some sort of permissions getting in the way of anki copying to your clipboard. Let me do some digging.

**Comment by AbdullahOmira** [comment]
I thought sso at first but it works with other addons
![image](https://user-images.githubusercontent.com/77205655/235991340-6d063c07-c8f0-4ed6-a1f7-fc946fb638ec.png)
![image](https://user-images.githubusercontent.com/77205655/235991417-73cf8004-2046-417f-9db4-f0ed3c8462ee.png)

**Comment by DoctorToBeIn23** [comment]
@abdnh would you be able to look into this, seems like there is a bug. This user is unable to get the QID numbers to export to his clipboard on windows.

**Comment by abdnh** [comment]
I pushed a fix.

**Comment by DoctorToBeIn23** [comment]
@AbdullahOmira could you let us know if this fixes your issue?

**Comment by AbdullahOmira** [comment]
@DoctorToBeIn23 abdullahomira25@gmail.com

**Comment by AbdullahOmira** [comment]
Thank you for the fix. it's working now 🙏

**Comment by Ngoyal95** [comment]
I am still having an issue with exporting QIDs with the newest addon version (1.2.0) - now whenever I try to export a list of QIDs from a selection of cards I get this error:

![image](https://github.com/AnKing-Memberships/ankiweb-placeholder/assets/9327832/23cfe325-887b-4888-9a37-881ba849795a)

I've tried many different Anking cards, and the "Export" function doesn't work with a large number of cards or even a single card.

I have also checked the log file AppData\Roaming\Anki2\addons21\607963104\user_files\already_exported_qids.json. and nothing is being exported to that file (however, imported QIDs do appear).

**Comment by DoctorToBeIn23** [comment]
@abdnh I think this push made it so Mac users are unable to export any QIDs. I tried on 2.1.55qt6 and 2.1.64qt6 and get this same message. @AnKingMed has also gotten the same issues when trying it.
![Screenshot 2023-06-13 at 11 43 38 PM](https://github.com/AnKing-VIP/ankiweb-placeholder/assets/60248099/108a874b-866e-44f3-968f-19ee1c1422e2)

**Comment by abdnh** [comment]
@DoctorToBeIn23 I found an unrelated issue that's probably causing this (both on Mac and PC). Can you toggle off auto mode and let me know if it works for you?

**Comment by AnKingMed** [comment]
@DoctorToBeIn23

**Comment by DoctorToBeIn23** [comment]
Fixed
